name: Java CI with Maven
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: jeffthamy17
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ecr: auto
          logout: true
      - name: LS
        run: ls -ltr
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jeffthamy17/job-manager:${{github.ref_name}}
