name: Java CI with Maven
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: jeffthamy17
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

            
