name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  setup:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 22-ea
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn -B clean test --file pom.xml
  clean:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clean target
        run: mvn -B clean --file pom.xml